version: '3'
services:
  web:
    build: .
    volumes:
      - .:/todo_rails_zw
    ports:
      - 3000:3000
    command: "bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - database_todo 
    links:
      - database_todo:database_todo
    stdin_open: true
  database_todo:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
